USE [SDM]
GO

/****** Object:  View [dbo].[v_rp_canceledorder_AOI]    Script Date: 2023/6/7 14:39:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[v_rp_canceledorder_AOI] as

SELECT COMPANY_ID,SECTION_ID,SOLD_TO,CUSTOMER_ID,
t1.ITEM_ID,QUANTITY,DUEQTY,TRANS_CURRENCY_ID,
UNIT_PRICE,EXT_AMT,FOREIGN_UNIT_PRICE,FOREIGN_AMT,
UNIT_COST,PRICE_FLAG,REQUEST_DATE,DELIVERY_DATE,
CANCEL_DATE,ORI_PROMISED_DATE,INVOICE_NO,SLIP_NO,
ARRANGE_FLAG,ALLOCATION_FLAG,WAREHOUSE_ID,
LAST_STATUS_ID,NEXT_STATUS_ID,IS_CANCELED,
TRANS_DATE,ORDER_NO,LINE_ID,ORDER_TYPE,ABBR,
CUSTOMER_NAME,CUSTOMER_INV,t1.ITEM_DESC,
PROMISE_DEL_DATE,SP_NO,ROUTE,
SALESMAN,CO_DEL_DATE,COREMARK,SHIP_WAY

  FROM [SDM].[dbo].[FACT_ORDERDETAIL_ALL_HISTORY] t1
  inner join lu_item t2 on t1.item_id=t2.item_id
  where year([CANCEL_DATE])*100+month([CANCEL_DATE])=year(dateadd(mm,-1,getdate()))*100+month(dateadd(mm,-1,getdate()))
    and t2.[TYPE_ID]='aoi'
GO


